import { GetStaticPropsContext } from 'next';
import Head from 'next/head';

export const getStaticProps = async ({ locale }: GetStaticPropsContext) => {
  return {
    props: {},
    revalidate: 60,
  };
};

export function Index() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-80 w-80 resize overflow-auto bg-blue-600">
        hi
      </div>
    </>
  );
}

export default Index;
